# Generated by Django 3.0.4 on 2020-05-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='97******19', max_length=12),
        ),
    ]
